# Generated by Django 4.2 on 2023-07-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('m', 'Man'), ('w', 'Woman'), ('k', 'Kids'), ('g', 'gift')], max_length=2),
        ),
    ]
